# SITE CONFIGURATION
baseurl: ""
url: "https://ssc-cio-office.github.io/"

# THEME-SPECIFIC CONFIGURATION
theme_settings:

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
include: ['_pages']
exclude:
  - Gemfile
  - Gemfile.lock
