# SITE CONFIGURATION
baseurl: ""

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
include: ['_pages']
exclude:
  - .circleci
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
